# -*- coding: utf-8 -*-
"""momo-discord-bot 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwHHAYclDtixSXGJl35xfovhxT5MaV8-
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile momo_scraper.py
# import requests
# from bs4 import BeautifulSoup
# 
# def scrape_iphone15_price():
#     url = "https://www.momoshop.com.tw/search/searchShop.jsp?keyword=iphone%2015"
#     headers = {
#         "User-Agent": "Mozilla/5.0"
#     }
#     res = requests.get(url, headers=headers)
#     soup = BeautifulSoup(res.text, "html.parser")
# 
#     products = soup.select(".prdListArea li")
#     results = []
# 
#     for product in products[:5]:  # 只取前 5 項作為範例
#         name_tag = product.select_one(".prdName")
#         price_tag = product.select_one(".price")
# 
#         if name_tag and price_tag:
#             name = name_tag.get_text(strip=True)
#             price = price_tag.get_text(strip=True)
#             results.append(f"{name} - {price}")
# 
#     return "\n".join(results) if results else "找不到商品資訊"
#

from flask import Flask, request, jsonify
from feebee_scraper import scrape_iphone15_price
import requests

DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1379337992317042688/aqp4lMDPPgrRFfxuYqhQSMiDKCht7-oP8hdCIRuDxNpJaJL90HwPzVFgFLsqtYlRrJcO"

app = Flask(__name__)

def send_to_discord(message):
    data = {"content": message}
    response = requests.post(DISCORD_WEBHOOK_URL, json=data)
    if response.status_code != 204:
        print("傳送失敗", response.text)

@app.route("/webhook", methods=["POST"])
def trigger_scraper():
    price_info = scrape_iphone15_price()
    send_to_discord(f"📱 iPhone 15 價格更新：\n{price_info}")
    return jsonify({"status": "ok", "message": "已送出 Discord"})

